const { APP_ENV } = process.env

export const QRCODE_LINK = 
  APP_ENV === 'dev' ? 'https://dev.pmssaas.com/h5/wanjia/qrcode/' : 
  APP_ENV === 'prod' ? 'https://b.pmssaas.com/h5/wanjia/qrcode/' : 
  'https://bb.pmssaas.com/h5/wanjia/qrcode/';

export const ACCESS_QRCODE_LINK = 
  APP_ENV === 'dev' ? 'https://dev.pmssaas.com/h5/wanjia/access/' : 
  APP_ENV === 'prod' ? 'https://b.pmssaas.com/h5/wanjia/access/' : 
  'https://bb.pmssaas.com/h5/wanjia/access/'; 

export const formItemHorizontalLayout = {
  style: { width: '100%' },
  labelCol: { span: 7 },
  wrapperCol: { span: 13 },
};

export const formItemLayout = {
  labelCol: {
    xs: { span: 24 },
    sm: { span: 7 },
  },
  wrapperCol: {
    xs: { span: 24 },
    sm: { span: 12 },
    md: { span: 10 },
  },
};

export const submitFormLayout = {
  wrapperCol: {
    xs: { span: 24, offset: 0 },
    sm: { span: 10, offset: 7 },
  },
};

export const MAX_UPLOAD_SIZE = 1024 * 1024 * 4;

export const pageSubMenu = {
  // 角色权限管理
  AUTH_MERCHANT_CREATE_OR_EDIT: '1-1-1',
  CHECK_AUTH_MERCHANT_DETAIL: '1-1-2',
  TOOGLE_AUTH_MERCHANT_STATUS: '1-1-3',
  AUTH_MERCHANT_SEARCH: '1-1-4',
  RESET_AUTH_MERCHANT_PWD: '1-1-5',

  ROLE_OPERATOR_CREATE_OR_EDIT: '1-2-1',
  CHECK_ROLE_OPERATOR_DETAIL: '1-2-2',
  ROLE_OPERATOR_SEARCH: '1-2-3',
  TOOGLE_ROLE_OPERATOR_STATUS: '1-2-4',

  CHECK_MERCHANT_OPERATOR_DETAIL: '1-3-1',
  MERCHANT_OPERATOR_SEARCH: '1-3-2',
  MERCHANT_OPERATOR_CREATE_OR_EDIT: '1-3-3',
  TOOGLE_MERCHANT_OPERATOR_STATUS: '1-3-4',
  RESET_MERCHANT_OPERATOR_PWD: '1-3-5',

  AUTH_ORG_CREATE_OR_EDIT: '1-4-1',
  AUTH_ORG_SEARCH: '1-4-2',

  AUTH_ROLE_CREATE_OR_EDIT: '1-5-1',
  CHECK_AUTH_ROLE_DETAIL: '1-5-2',
  AUTH_ROLE_SEARCH: '1-5-3',
  TOOGLE_AUTH_ROLE_STATUS: '1-5-4',

  AUTH_OPERA_CREATE_OR_EDIT: '1-6-1',
  TOOGLE_AUTH_OPERA_STATUS: '1-6-2',
  CHECK_AUTH_OPERA_DETAIL: '1-6-3',
  AUTH_OPERA_SEARCH: '1-6-4',
  RESET_AUTH_OPERA_PWD: '1-6-5',

  // 商户管理
  MERCHANT_CREATE_OR_EDIT: '2-1-1',
  AUDIT_MERCHANT: '2-1-2',
  TOOGLE_MERCHANT_STATUS: '2-1-3',
  CHECK_MERCHANT_DETAIL: '2-1-4',
  UPDATE_MERCHANT: '2-1-5',
  MERCHANT_SEARCH: '2-1-6',
  MERCHANT_EXPORT: '2-1-7',

  MERCHANT_AUDIT_SEARCH: '2-2-1',
  AUDIT_MERCHANT_AUDIT: '2-2-2',
  CHECK_MERCHANT_AUDIT_DETAIL: '2-2-3',

  // 缴费管理
  CHECK_PAYMENT_MODE_DETAIL: '3-1-1',
  PAYMENT_MODE_SEARCH: '3-1-2',
  PAYMENT_MODE_CREATE_OR_EDIT: '3-1-3',
  DELETE_PAYMENT_MODE: '3-1-4',

  PAYMENT_FEE_TYPE_CREATE_OR_EDIT: '3-2-1',

  PAYMENT_CALL_SEARCH: '3-3-1',
  PAYMENT_CALL_CREATE: '3-3-2',
  CHECK_PAYMENT_CALL_DETAIL: '3-3-3',
  PAYMENT_CALL_EXPORT: '3-3-4',

  // 账单管理
  BILL_CREATE_OR_EDIT: '4-1-1',
  CHECK_BILL_DETAIL: '4-1-2',
  BILL_EXPORT: '4-1-3',
  BILL_RECORD_REFUND: '4-1-4',
  BILL_SEARCH: '4-1-5',
  CALL_TEMP_CREATE_BILL: '4-1-6',
  TOGGELE_BILL_STATUS: '4-1-7',
  BILL_IMPORT: '4-1-9',
  BILL_BATCH_CREATE: '4-1-10',

  TOGGELE_BILL_TEMP_STATUS: '4-2-1',
  BILL_TEMP_CREATE_OR_EDIT: '4-2-2',
  CHECK_BILL_TEMP_DETAIL: '4-2-3',
  BILL_TEMP_SEARCH: '4-2-4',
  BILL_TEMP_CALL_LOG: '4-2-5',

  ONSITE_PAYMENT_SEARCH: '4-4-1',
  ONSITE_BATCH_PAYMENT: '4-4-2',
  CHECK_ONSITE_PAYMENT_DETAIL: '4-4-3',

  BILL_PRINT_SEARCH: '4-5-1',
  CHECK_BILL_PRINT_DETAIL: '4-5-3',
  BILL_PRINT: '4-5-4',

  // 订单管理
  PAY_ORDER_SEARCH: '5-1-1',
  CHECK_PAY_ORDER_DETAIL: '5-1-2',
  PAY_ORDER_EXPORT: '5-1-3',
  PAY_ORDER_REFUND: '5-1-4',

  BUSINESS_ORDER_SEARCH: '5-2-1',
  CHECK_BUSINESS_ORDER_DETAIL: '5-2-2',
  BUSINESS_ORDER_EXPORT: '5-2-4',

  // 信息管理
  COMMUNITY_CREATE_OR_EDIT: '6-1-1',
  TOGGELE_COMMUNITY_STATUS: '6-1-2',
  CHECK_COMMUNITY_DETAIL: '6-1-3',
  DOWNLOAD_COMMUNITY_QRCODE: '6-1-4',
  COMMUNITY_SEARCH: '6-1-5',
  DOWNLOAD_COMMUNITY_CASHIER_QRCODE: '6-1-6',
  COMMUNITY_EXPORT: '6-1-7',
  DOWNLOAD_ACCESS_QRCODE: '6-1-8',

  HOUSE_CREATE_OR_EDIT: '6-2-1',
  TOGGELE_HOUSE_STATUS: '6-2-2',
  CHECK_HOUSE_DETAIL: '6-2-3',
  DOWNLOAD_HOUSE_QRCODE: '6-2-4',
  HOUSE_SEARCH: '6-2-5',
  HOUSE_EXPORT: '6-2-6',
  HOUSE_IMPORT: '6-2-8',

  RESIDENT_CREATE_OR_EDIT: '6-3-1',
  TOGGELE_RESIDENT_STATUS: '6-3-2',
  CHECK_RESIDENT_DETAIL: '6-3-3',
  RESIDENT_SEARCH: '6-3-4',
  RESIDENT_EXPORT: '6-3-5',
  RESIDENT_IMPORT: '6-3-6',

  // 物业服务管理
  MACINTAIL_ALL_OPERATION: '7-2-1',
  MACINTAIL_ALL_MERCHANT: '7-2-2',

  STATION_CREATE_OR_EDIT: '7-3-1',
  TOGGELE_STATION_STATUS: '7-3-2',
  STATION_SEARCH: '7-3-3',

  EMPLOYEE_CREATE_OR_EDIT: '7-4-1',
  TOGGELE_EMPLOYEE_STATUS: '7-4-2',
  EMPLOYEE_SEARCH: '7-4-3',
  CHECK_EMPLOYEE_DETAIL: '7-4-4',

  CREATE_ACCESS: '7-5-1',
  DELETE_ACCESS: '7-5-2',
  ACCESS_SEARCH: '7-5-3',
  ACCESS_EXPORT: '7-5-4',

  // 报表管理
  RECONCILIATION_REPORT_ORDER_SEARCH: '8-1-1',
  RECONCILIATION_REPORT_ORDER_DOWNLOAD: '8-1-3',

  MERCHANT_SETTLEMENT_SEARCH: '8-2-1',
  MERCHANT_SETTLEMENT_EXPORT: '8-2-2',

  COMMUNITY_COLLECTION_SEARCH_OR_EXPORT: '8-3-1',
  COMMUNITY_COLLECTION_SEARCH_OR_EXPORT_MERCHANT: '8-3-2',
  
  MERCHANT_COLLECTION_SEARCH_OR_EXPORT: '8-4-1',
  
  COMMUNITY_CODE_COLLECTION_SEARCH: '8-5-1',
  COMMUNITY_CODE_COLLECTION_EXPORT: '8-5-2',
  CHECK_COMMUNITY_CODE_COLLECTION_DEATIL: '8-5-3',

  // 运营数据
  OPERATE_RECONCILIATION_SEARCH: '9-2-2',
  CHECK_OPERATE_RECONCILIATION_DETAIL: '9-2-3',
  RENEW_OPERATE_RECONCILIATION: '9-2-4',

  // 参数管理
  ICON_TEMP_CREATE_OR_EDIT: '10-1-1',
  CHECK_ICON_TEMP_DETAIL: '10-1-2',
  ICON_TEMP_SEARCH: '10-1-3',
  ICON_TEMP_DEFAULT: '10-1-4',

  HOME_CONFIG_CREATE_OR_EDIT: '10-2-1',
  TOGGELE_HOME_CONFIG_STATUS: '10-2-2',
  CHECK_HOME_CONFIG_DETAIL: '10-2-3',
  HOME_CONFIG_SEARCH: '10-2-4',

  CUSTOMER_CHANNEL_CREATE_OR_EDIT: '10-3-1',
  TOGGELE_CUSTOMER_CHANNEL_STATUS: '10-3-2',
  CHECK_CUSTOMER_CHANNEL_DETAIL: '10-3-3',
  CUSTOMER_CHANNEL_SEARCH: '10-3-4',

  SCROLL_BANNER_CREATE_OR_EDIT: '10-4-1',
  CHECK_SCROLL_BANNER_DETAIL: '10-4-2',
  SCROLL_BANNER_SEARCH: '10-4-3',
  SCROLL_BANNER_DEFAULT: '10-4-4',

  ADVERTISEMENT_CREATE_OR_EDIT: '10-5-1',
  CHECK_ADVERTISEMENT_DETAIL: '10-5-2',
  ADVERTISEMENT_SEARCH: '10-5-3',

  BOTTOM_BANNER_CREATE_OR_EDIT: '10-6-1',
  CHECK_BOTTOM_BANNER_DETAIL: '10-6-2',
  BOTTOM_BANNER_SEARCH: '10-6-3',
  BOTTOM_BANNER_DEFAULT: '10-6-4',

  SMS_SEARCH: '10-7-1',
  SMS_CREATE_OR_EDIT: '10-7-2',
  CHECK_SMS_DETAIL: '10-7-3',
  TOGGELE_SMS_STATUS: '10-7-4',

  SMS_AUDIT_SEARCH: '10-8-1',
  SMS_AUDIT: '10-8-2',
  CHECK_SMS_AUDIT_DETAIL: '10-8-3',

  // 消息管理
  NOTICE_CREATE_OR_EDIT: '11-1-1',
  NOTICE_UNDER: '11-1-2',
  CHECK_NOTICE_DETAIL: '11-1-3',
};

